### ISSUE TITLE
failure: repodata/repomd.xml from delorean-current-tripleo: [Errno 256] No more mirrors to try

### ISSUE THREAD

**Issue by zeeshanalisyed** [cybertron/tripleo-repos#1]
I tried to execute below given commands 
### current
```bash
$ sudo tripleo-repos current
```
```bash
$ sudo tripleo-repos -b mitaka current
```
### current-tripleo
```bash
$ sudo tripleo-repos current-tripleo
```
### current-tripleo-dev
```bash
$ sudo tripleo-repos current-tripleo-dev
```
All Commands end up with the below given error
```
failure: repodata/repomd.xml from delorean-current-tripleo: [Errno 256] No more mirrors to try.
https://trunk.rdoproject.org/centos7/af/f5/aff5d8f30d73cf34e9a52a0b070143f128e37e79_57e4b623/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
```
### Screenshot
![Screenshot from 2021-05-04 10-23-33](https://user-images.githubusercontent.com/8758274/116967277-ff318380-acc2-11eb-912e-c01c4d787437.png)

### OS
Version: Centos7

**Comment by cybertron** [comment]
This repo is extremely out of date. The current version of the code lives at https://opendev.org/openstack/tripleo-repos. Please try again with that and report bugs as described in https://opendev.org/openstack/tripleo-repos/src/branch/master/CONTRIBUTING.rst

**Comment by zeeshanalisyed** [comment]
> This repo is extremely out of date. The current version of the code lives at https://opendev.org/openstack/tripleo-repos. Please try again with that and report bugs as described in https://opendev.org/openstack/tripleo-repos/src/branch/master/CONTRIBUTING.rst

I don't find any tripleo.sh file where is that?

**Comment by cybertron** [comment]
It's possible the readme is out of date. I don't work on TripleO anymore so I'm not sure what the current method is. I suggest contacting the current TripleO development team for more information.
